export const getLogs = async () => {
  const logs = [
    {
      id: 1,
      host: 'localhost',
      microserviceName: "INTEGRATIONS_WORKER",
      orderReference: "20240319ER0",
      customerReference: "09869765986987156087",
      level: "info",
      age: "29",
      email: "tony.reichert@example.com",
      message: "Order created successfully",
      data: {},
      errorData: {},
      timestamp: new Date().toISOString(),
    },
    {
      id: 2,
      host: 'localhost',
      microserviceName: "INTEGRATIONS_WORKER",
      orderReference: "20240319ER0",
      customerReference: "09869765986987156087",
      level: "info",
      age: "29",
      email: "tony.reichert@example.com",
      message: "Order created successfully",
      data: {},
      errorData: {},
      timestamp: new Date().toISOString(),
    },
    {
      id: 3,
      host: 'localhost',
      microserviceName: "INTEGRATIONS_WORKER",
      orderReference: "20240319ER0",
      customerReference: "09869765986987156087",
      level: "error",
      age: "29",
      email: "tony.reichert@example.com",
      message: "Order created successfully",
      data: {},
      errorData: {},
      timestamp: new Date().toISOString(),
    },
    {
      id: 4,
      host: 'localhost',
      microserviceName: "INTEGRATIONS_WORKER",
      orderReference: "20240319ER0",
      customerReference: "09869765986987156087",
      level: "info",
      age: "29",
      email: "tony.reichert@example.com",
      message: "Order created successfully",
      data: {},
      errorData: {},
      timestamp: new Date().toISOString(),
    },
    {
      id: 5,
      host: 'localhost',
      microserviceName: "INTEGRATIONS_REST",
      orderReference: "20240319ER0",
      customerReference: "09869765986987156087",
      level: "info",
      age: "29",
      email: "tony.reichert@example.com",
      message: "Order created successfully",
      data: {},
      errorData: {},
      timestamp: new Date().toISOString(),
    },
    {
      id: 6,
      host: 'localhost',
      microserviceName: "INTEGRATIONS_WORKER",
      orderReference: "20240319ER0",
      customerReference: "09869765986987156087",
      level: "dangerous",
      message: "Order created successfully",
      data: {},
      errorData: {},
      timestamp: new Date().toISOString(),
    },
  ];

  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(logs);
    }, 1000);
  });
}
